#ifndef RESOURCES_H
#define RESOURCES_H

#define IDC_PATH_EDITBOX 50
#define IDC_PATH_BROWSEBTN 51
#define IDC_PATH_EDITBOXX64 52
#define IDC_PATH_BROWSEBTNX64 53
#define IDC_BROWSELABEL 54
#define IDC_BROWSELABEL_X64 55
#define IDC_TOOLS_GROUPBOX 56
#define IDC_DOWNLOADTOOLS_CHECKBOX 57
#define IDC_TOOLSPATH_LABEL 58
#define IDC_TOOLSPATH_EDITBOX 59
#define IDC_TOOLSPATH_BROWSE_BTN 60
#define IDC_PATCH_BTN 61
#define IDC_REVERT_PATCH_BTN 62
#define IDC_PROGRESSBAR 63
#define IDC_STATUSBAR 64

#endif